nucleuscloud/neosync

frontend/app/connections/[id]/components/PostgresForm.tsx
frontend/app/new/connection/postgres/PostgresForm.tsx
frontend/yup-validations/connections.ts

from benthos docs
`Please note that the postgres driver enforces SSL by default, you can override this with the parameter sslmode=disable if required.`

set default ssl mode to disable

---

frontend/app/jobs/[id]/components/RecentRuns.tsx

ID column now links to job run
hovering over arrow now shows href

updates recentruns table to link via id and show href on action arrow

---

.github/workflows/devcontainer-release.yml

The `devcontainers/ci` action assumes that multi-platform image builds aren't possible and injects an `--output` flag to download the image as a tarball instead. This isn't the case with Depot, as it can build multi-platform images directly.
This PR adapts the workflow to call the `devcontainer` CLI directly, so that the build and push can function as expected.

Use devcontainers CLI directly

---

.github/workflows/artifact-release.yml

Adds permission scopes to allow provenance publishing
https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow

NEOS-479 updates npm publish gha permissions

---

frontend/apps/web/app/[account]/settings/api-keys/[id]/page.tsx
frontend/apps/web/components/ui/alert.tsx

* Success alert now rendering properly in dark mode
* Fixes regression where keyvalue was not being checked causing the input box to always show

Fixes API Key Input Box showing all the time, Fixes dark mode Success alert

---

backend/services/mgmt/v1alpha1/job-service/jobs.go
backend/services/mgmt/v1alpha1/job-service/jobs_test.go
frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx

there was frontend bug when updating job source. It was finding the wrong source connection. updated backend to check job source option config type matches job source connection type.

fix update job source bug

---

backend/charts/api/templates/api-env-vars.yaml
backend/charts/api/templates/deployment.yaml
backend/charts/api/templates/role-binding.yaml
backend/charts/api/templates/role.yaml
frontend/apps/web/charts/app/templates/app-env-vars.yaml
frontend/apps/web/charts/app/templates/deployment.yaml
worker/charts/worker/templates/deployment.yaml
worker/charts/worker/templates/env-vars.yaml

- [all] Made `shutdownTimeoutSeconds` an optional field
- [all] Made `terminationGracePeriod` an optional field
- [api] Made `neosyncCloud.workerApiKeys` an optional field
- [api] Fixed the `namespace` for the role and role-binding so it's based on the chart release
- [app] Made `neosyncApi.url` an optional field

Helm chart fixes

---

backend/gen/go/db/mock_Querier.go
backend/gen/go/db/users.sql.go
backend/services/mgmt/v1alpha1/user-account-service/users_test.go
backend/sql/postgresql/queries/users.sql

Fetching GetUserAccounts with an API key as the auth mechanism will now properly return the account that the API key is associated with.

Updates GetUserAccounts to support account-scoped API Keys

---

frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/RecentRuns.tsx
frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunStatus.tsx

Also changes the recent job run refresh to happen on the trigger button
triggering a job no longer routes you back to the home page and keeps you on the page you were currently on.
adds tooltip to unknown status explaining what it means.

Updates job run status to use unknown instead of archive

---

worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go

If there is no max length, it defaults to -1, which was bugging out the min/max length constraint checks

Adds fix for character max length check

---

README.md

This PR corrects a broken link in the README.md file, facilitating seamless access to the local dev documentation.

Fix invalid local-dev guide link in README

---

backend/pkg/table-dependency/table-dependency.go
backend/pkg/table-dependency/table-dependency_test.go
cli/internal/cmds/neosync/sync/sync.go
worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
worker/pkg/workflows/datasync/workflow/workflow.go

fixes truncate before insert with circular dependencies
fixes ordering issue with circular dependencies

Fix circular dependencies

---

frontend/apps/web/components/DualListBox/ColumnHeader.tsx

gets rid of the popup menu in favor of it all just being inline for faster searching,filtering and less pops ups to click away

updates dual list box header search and sort states

---

Makefile
worker/internal/benthos/transformers/transform_first_name.go
worker/internal/benthos/transformers/transform_float.go
worker/internal/benthos/transformers/transform_full_name.go
worker/internal/benthos/transformers/transform_lastname.go

misunderstood how the functions were calculated. functions in benthos are memoized by their inputs.
for transformers, this may be different every time due to us passing in values. 
updated it to work with defaults better. this will still pose an issue if the seed value is present.

fixes transformer seeds that resulted in them being the same

---

docs/docs/overview/core-features.mdx

The old link to `/platform#transformers` lands on a page with no information about transformers: 
Updates the links to point to https://docs.neosync.dev/transformers/introduction

[Docs] fix transformers links

---

docs/docs/overview/introduction.mdx

Removes errant semicolon on the docs introduction page at the end of the first section (below the image). 
Before: 
After:

[Docs] Remove extra semicolon from docs page

---

backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
backend/gen/go/db/dbschemas/postgresql/querier.go
backend/gen/go/db/dbschemas/postgresql/system.sql.go
backend/pkg/dbschemas/sql/postgresql/queries/system.sql
backend/pkg/sqlmanager/mock_SqlDatabase.go
backend/pkg/sqlmanager/mysql-manager.go
backend/pkg/sqlmanager/postgres-manager.go
backend/pkg/sqlmanager/postgres-manager_test.go
backend/pkg/sqlmanager/sql-manager.go
backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
backend/services/mgmt/v1alpha1/connection-data-service/connection-data_test.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go

This PRs adds Postgres support for init tables:
1. custom data types
2. custom functions
3. custom triggers
4. custom sequences
This will be specific to job mappings selected, so it will only contextually bring over anything that is relevant to the mapped tables in a specific job.

NEOS-1129 add support for initing PG custom data types, etc

---

compose.yml

This addresses the common issue of flag incompatibility between latest `temporalio/admin-tools` setup.
ISSUE REF: https://github.com/nucleuscloud/neosync/issues/2046

NEOS-1126 fix(compose): pin admin-tools version to v1.23

---

backend/gen/go/db/dbschemas/mysql/mock_Querier.go
backend/gen/go/db/dbschemas/mysql/querier.go
backend/gen/go/db/dbschemas/mysql/system.sql.go
backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
backend/gen/go/db/dbschemas/postgresql/querier.go
backend/gen/go/db/dbschemas/postgresql/system.sql.go
backend/pkg/dbschemas/sql/mysql/queries/system.sql
backend/pkg/dbschemas/sql/postgresql/queries/system.sql
backend/pkg/sqlmanager/mock_SqlDatabase.go
backend/pkg/sqlmanager/mysql/mysql-manager.go
backend/pkg/sqlmanager/mysql/mysql-manager_test.go
backend/pkg/sqlmanager/postgres/postgres-manager.go
backend/pkg/sqlmanager/postgres/postgres-manager_test.go
backend/pkg/sqlmanager/sql-manager.go
backend/services/mgmt/v1alpha1/connection-service/connection.go
frontend/apps/web/components/permissions/PermissionsDataTable.tsx
frontend/apps/web/components/permissions/columns.tsx

This solves the issue where the role name used isn't the underlying role that makes it to the database.
Prime example here is subabase gives a user like `postgres.<tenant>` whereas the underlying postgres user is still just `postgres`.
By using the `current_user` sql, we don't have to concern ourselves with the user from the connection and can just use the authenticated user.

NEOS-1177 Fixes role check query to use current_user

---

docs/docs/overview/quickstart.mdx

Having a default value simplifies how table values can be created and doesn't interfere with the transform job.

Add default UUID value to users.id

---

.github/workflows/pull-request.yml

This PR adds a new Github Action, the action checks if there is atleast one PR label present, if not it makes a comment in the PR. This PR addresses issue #2294
- Opening a PR without a label
- Adding a label after said comment

workflow: add github action for checking pr label

---

compose.yml

changed Dockerfile added network `temporal-network`, and changed temporalio/admin-tools, from 1.23 to 1.23.0
Closes #2356

added 'temporal-network' network and changed temporalio/admin-tools

---

worker/pkg/benthos/dynamodb/input.go
worker/pkg/benthos/dynamodb/input_test.go
worker/pkg/benthos/dynamodb/mock_dynamoDBAPIV2.go

Prepares us for enabling user-defined subsetting for dynamodb

NEOS-1290: updates benthos dynamodb input to use partiql instead of scan

---

worker/pkg/benthos/dynamodb/input.go

Was improperly parsing some credentials

NEOS-1298: Fixes Benthos DynamoDB Input AWS Creds Parser

---

docs/docs/transformers/gen-javascript-transformer.md
worker/pkg/benthos/transformers/gen_generate_int64.go
worker/pkg/benthos/transformers/generate_bool.go
worker/pkg/benthos/transformers/generate_email.go
worker/pkg/benthos/transformers/generate_first_name.go
worker/pkg/benthos/transformers/generate_float.go
worker/pkg/benthos/transformers/generate_full_name.go
worker/pkg/benthos/transformers/generate_gender.go
worker/pkg/benthos/transformers/generate_int64.go
worker/pkg/benthos/transformers/generate_last_name.go
worker/pkg/benthos/transformers/generate_ssn.go
worker/pkg/benthos/transformers/generate_username.go
worker/pkg/benthos/transformers/transform_email.go
worker/pkg/benthos/transformers/transform_first_name.go
worker/pkg/benthos/transformers/transform_float.go
worker/pkg/benthos/transformers/transform_full_name.go
worker/pkg/benthos/transformers/transform_lastname.go
worker/pkg/benthos/transformers/utils/integer_utils.go

This was causing the generated values to be the same every time inbetween runs in the default case.

NEOS-1295: moves seed to be deferred for transformations

---

go.mod
go.sum

go mod tidy after updating parquet
merging this will allow it to build under go 1.23:
https://github.com/parquet-go/parquet-go/commit/c140e8fd7aca32892781f866923304f88b769a5a

update parquet to support go version 1.23

---

frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SelectModelNames.tsx

Also removes gpt-4 as it hasnt worked in months. Removes 3.5 as it's recommended by openai to be replaced by 4-o-mini

updates default openai common models to document latest gpt models

---

backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
backend/pkg/sqlmanager/shared/utils.go
backend/pkg/sqlmanager/shared/utils_test.go

Bug was in dedupe slice which was not preserving order.

NEOS-1381: fixes inconsistent ordering of mssql constraints

---

frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
frontend/apps/web/yup-validations/jobs.ts

Adding in support for editing mongo db mappings in line. 
The user can now press the edit button after a mapping has been added and then edit it right there and then click on the check icon to save it right after. 
Clicking on the save icon updates the form but will not persist across reloads unless the user hits the 'update' button, as we have it with other updates as well.

NEOS-1361, NEOS-1370: Support updating mongo mappings inline

---

frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
frontend/apps/web/components/jobs/NosqlTable/data-table-row-actions.tsx

This adds support for one-click duplicating mapping rows in the nosql mapping table so that as a user you don't have to recreate the entire mapping from scratch. This is helpful if you have a deeply nested object and want to map it's elements. Instead of writing out the entire path every time, you can just duplicate they key and then update the leaf. 
Duplicating a row appends a `_{num}` to the end. Duplicating the same row over and ovre again, increments the `num`. 
This takes the collection into consideration as well and treats the entire row of collection.key as a unique key. 
https://www.loom.com/share/b2ca663c0ef4498a8b47a9fc8436edea?sid=03b2fe45-015c-4a0b-ac86-53c798e29663

NEOS-1389: adds support for duplicating nosql mapping rows

---

backend/gen/go/db/dbschemas/postgresql/system.sql.go
backend/pkg/dbschemas/sql/postgresql/queries/system.sql
backend/pkg/sqlmanager/postgres/integration_test.go
backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
backend/pkg/sqlmanager/postgres/testdata/setup.sql
backend/pkg/sqlmanager/postgres/testdata/teardown.sql

Adds support for special characters in postgres schemas and tables.
This does not currently support schemas/tables with double quotes.
Fast follow in Github: https://github.com/nucleuscloud/neosync/issues/2591

NEOS-1393: adds support for postgres special characters except for double quotes

---

frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
frontend/apps/web/components/jobs/NosqlTable/data-table-row-actions.tsx

A few updates to make making mongo mappings more performant. 
Abstracts the onDuplicate() function into a callback that gets called in the parent component.
Reworks the unique mapping creation to create a unique identifier instead of using an int.

updates duplicate mapping functinality to be more performant

---

frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCardNumber.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCategoricalForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCountryForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateEmailForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateGenderForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInt64Form.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInternationalPhoneNumberForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStateForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringPhoneNumberForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateUuidForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformE164PhoneNumberForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformEmailForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFirstNameForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFloat64Form.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFullNameForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64Form.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64PhoneForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformLastNameForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformPhoneNumberForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformStringForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
frontend/apps/web/components/ListBox/ListBox.tsx
frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
frontend/apps/web/components/ui/form.tsx

This updates styling across most of the forms in the app to reduce the "jumping" of the UI when there is an error. It gives the <FormMessage /> component a static height, even if there is no error, so when there is an error it just fills the space without causing the rest of the UI to shift down.

NEOS-1403:update forms to not shift on errors

---

.gitignore
Makefile
backend/dev/build/.air.toml
backend/dev/build/Dockerfile.dev
backend/services/mgmt/v1alpha1/user-account-service/users.go
compose.dev.yml
compose/temporal/compose.yml
docs/docs/guides/neosync-local-dev.md
frontend/apps/web/dev/build/Dockerfile.dev
worker/cmd/worker/main.go
worker/dev/build/.air.toml
worker/dev/build/Dockerfile.dev

frontend is largely unchanged.
Backend/Worker now use `air` to rebuild directly inside of the container.

Replaces Docker Compose Watch with Bind Mounts

---

frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx

Updates the schema mapping table max height to 1000px.

NEOS-1459: update schema page table max height

---

frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
frontend/apps/web/components/jobs/SchemaTable/SchemaTableViewOptions.tsx

This is a feature and a bug fix.
This removes the ability to game the bulk transformer filtering by disabling the apply button based on the allowed transformers.
This also adds a warning icon with a tooltip to explain why the button is disabled.
Demo: https://www.loom.com/share/41a5ae4422564f68a807d22b98834478

NEOS-1453: disables bulk transformer button based on selected rows

---

docs/docs/transformers/system.md
frontend/apps/web/app/(mgmt)/[account]/connections/[id]/permissions/page.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateJavascriptForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformJavascriptForm.tsx
frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
frontend/apps/web/app/(mgmt)/[account]/transformers/systemTransformers/[source]/page.tsx
frontend/apps/web/components/headers/PageHeader.tsx
frontend/apps/web/components/labels/LearnMoreLink.tsx
frontend/apps/web/components/permissions/PermissionsDialog.tsx

This features adds a "Learn More" link that points to the specific Transformer being inspected/selected. 
Updated:
1. System Transformers [id] page
2. Custom Transformers [id] page
3. Create new Custom Transformer page
4. Transformer Dialog in Mapping page
https://www.loom.com/share/632ff6d558954d86a411166f679f2659?sid=c9c5dc70-295c-45c8-ab5d-0b2cc788899d

NEOS-1462: Add transformer links to app

---

backend/pkg/sshtunnel/tunnel.go

Updates a common (unavoidable) error to be a warning.
Adds more debug logging to bastion host.
Took some time to rework the host to be much easier to read and better handle connection leaks.
I've had to manually test this since we don't have reliable integration tests for tunneling yet.

Reduces bastion host network error logs

---

frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
frontend/apps/web/components/headers/SubPageHeader.tsx
frontend/apps/web/components/site-header/SiteHeader.tsx
frontend/apps/web/components/site-header/Upgrade.tsx
frontend/apps/web/components/site-header/UpgradeButton.tsx
frontend/apps/web/components/ui/dialog.tsx

* Updated billing page to be more responsive
* Updated billing header to use page sub header to render more like other pages
* Updates upgrade button in site header to include a new account status dialog
* Text could probably use some word smithing
Demo: https://www.loom.com/share/d81586a5a2fb4bf19aa0b4dee70837bb

NEOS-1472: add frontend banner that displays account status

---

compose.dev.yml
frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx

This feature adds a running timer to the duration stat card in the run/[id] page. Gives users an idea of how long a job is taking. I noticed this when I was working with a customer that they were looking at the timer as a way of seeing if they were getting past the issue i.e. the last job failed at 25 seconds, now that we're at 40 seconds, we likely resolved that. 
The timer is pretty close but not perfect, in that it usually goes over by 2-3 seconds but then updates to the final time once it's there. That's also just locally, in prod it likely is better. 
This handles the minutes and seconds conversions as well so if it goes over 59 seconds it will change from '59 seconds' to '1 minute 1 second'. It also handles plural seconds and minutes. It does not go into hours. Can make that a fast …

NEOS-1449: adds a running timer to the run id page

---

worker/charts/worker/templates/deployment.yaml

An empty label can cause issues in the deployment.
A solution could be setting a default value but I could not think of one that wouldn't interfer with the user. This is another posibility.

Fix(worker-chart): remove empty label if value not set

---

backend/charts/api/README.md
backend/charts/api/templates/deployment.yaml
backend/charts/api/values.yaml
backend/dev/helm/api/values.yaml
charts/neosync/README.md

Took https://github.com/nucleuscloud/neosync/pull/2602 over the line to get the feature in.
Should also help out https://github.com/nucleuscloud/neosync/pull/2714

Adds extraEnvVars to api deployment init container for db migrations

---

backend/charts/api/templates/deployment.yaml
frontend/apps/web/charts/app/templates/deployment.yaml

Related to https://github.com/nucleuscloud/neosync/pull/2715
I had only done one third of the task yesterday.

feat(charts): make nucleusEnv an optional label for all charts

---

worker/pkg/benthos/javascript/functions.go
worker/pkg/benthos/javascript/functions_test.go
worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors_test.go

This makes sure that only columns that have JS transformers set are updated. Prevents unnecessary conversion of all column values from Javascript back to golang

NEOS-1433 Updates javascript transformer to use patch function

---

backend/internal/cmds/mgmt/run/stripe-usage/cmd.go
backend/internal/cmds/mgmt/serve/connect/cmd.go
internal/otel/otel.go
worker/internal/cmds/worker/serve/serve.go

- Fixes issue where tracer is disabled but still gets added to the shutdowns array. This was causing a nil pointer error on process shutdown
- Enables Connect Client tracing and metering for worker when it communicates to the API for better traces and more metrics
- Inverts configuration for text map propagator
- Adds new env var to allow switching temporality for benthos metrics

OpenTelemetry Updates for Worker, Stripe, Backend

---

backend/services/mgmt/v1alpha1/connection-service/connection.go
frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
frontend/apps/web/components/connections/TestConnectionBadge.tsx

This PR does two things:
- Updates the UI to no longer show the Connection error for any unsupported connections
- Fixes issue in the test connection badge where we were double nested <a /> tags
What is shown today in prod for S3 destinations:
Now nothing is shown:
Here is an image of the failed connect badge after removing the double anchor (to show there are no style changes):

NEOS-1516: updates to not show any connect errors for unsupported connections

---

frontend/apps/web/components/RunTImeline/RunTimeline.tsx

Adds an expandable modal to each row in the Run Timeline table. When expanded, there are additional details about the subtasks of the activity, when they run and how long they took. 
The start time has been updated to actually be the scheduled time now instead of the original start time. This is so the duration of the activity aligns with the individual sub tasks when we render them.

NOES-1523:adding an expanded modal to the runs timeline

---

internal/ee/transformers/functions/functions.go
internal/ee/transformers/functions/functions_test.go

- We were providing our own default anonymizer which did a replace with `<REDACTED>` this updates it to use the system default which replaces with the named entity.

NEOS-1561: updates logic to use presidio defined default if no user provided value

---

docs/blog/2024-10-10-cli-sync.md
docs/blog/2024-10-24-anonymization-api.md

accidently mixed dates up - updated

update changelog body

---

frontend/apps/web/components/FileUpload/FileUpload.tsx

Minor dark mode styling updates:
Before:
After:

NEOS-1592:add dark mode stylings to upload component

---

worker/pkg/benthos/config.go
worker/pkg/benthos/sql/deadlock.go
worker/pkg/benthos/sql/deadlock_test.go
worker/pkg/benthos/sql/output_sql_insert.go
worker/pkg/benthos/sql/output_sql_update.go
worker/pkg/benthos/sql/retry.go
worker/pkg/benthos/sql/retry_test.go

Deadlocks can occur in highly concurrent environments, even when inserting to a single table.
This adds support for retries to help smooth this out ahead of us adding the ability to configure the batch size, max in flight, and even the retry configurations.

NEOS-1585: Adds deadlock retry support to SQL outputs

---

cli/internal/cmds/neosync/sync/sync_integration_test.go
internal/benthos/benthos-builder/builders/sql.go
internal/testutil/utils.go
worker/pkg/benthos/config.go
worker/pkg/benthos/environment/environment.go
worker/pkg/benthos/sql/json_processor.go
worker/pkg/benthos/sql/json_processor_test.go
worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/insert.sql

Fixes: 
- bit columns
- json columns with string as value
Postgres Broken
- money
- timetz
- all arrays

Fix S3 to SQL database types

---

.github/dependabot.yml

adds myself as a reviewer so i'm aware of request.
Specifies versioning strategy on frontend to get dependabot working again for the monorepo.

sets versioning strat on frontend to force package updates

---

backend/internal/cmds/mgmt/serve/connect/cmd.go
backend/internal/connect/interceptors/bookend/interceptor.go
backend/internal/connect/interceptors/bookend/interceptor_test.go

- renamed "logging" interceptor to "bookend" for better clairty
- exposed the ability to configure the log level. was thinking maybe we'd eventually want another one higher up in the chain at the debug level or something (prob overkill)
- moved the bookend logger to be the last mw option in the stack to benefit from more attributes like the accountId and auth user information.
This will now tag the `userId` in every auth'd request where it is present giving us much more insight into who is doing what during debug sessions.

Moves bookend logger lower in mw stack to benefit from more attrs

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Neosync Guru](https://gurubase.io/g/neosync) to Gurubase. Neosync Guru uses the data from this repo and data from the [docs](https://docs.neosync.dev) to answer questions by leveraging the LLM.
In this PR, I showcased the "Neosync Guru", which highlights that Neosync now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me …

Introducing Neosync Guru on Gurubase.io

---

frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
frontend/apps/web/components/jobs/JobMappingTable/ConstraintsCell.tsx

Also re-adds truncated text for longer schema/tables

NEOS-1631: reduce constraint text

---

backend/services/mgmt/v1alpha1/job-service/jobs.go

We were previously logging each error from temporal schedule with the same message. This PR updates that to be unique for better tracking.
Also when describing job statuses, we were layering in the wrong error message, that has been fixed. - It has also been updated to a warn as this error is common when job runs have been archived.

NEOS-1625: updates temporal schedule errors to be unique

---

backend/dev/build/Dockerfile.dev
backend/internal/cmds/mgmt/serve/connect/cmd.go
backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
worker/dev/build/Dockerfile.dev

- Fixes nil pointer
- Pins air in worker/backend dockerfile devs due to go version mismatch
- adds log for neosync cloud for easier debugging

NEOS-1634: Fixes AnonymizeSingle nil pointer exception on error

---

frontend/apps/web/components/TruncatedText.tsx
frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
frontend/apps/web/util/util.ts

This PR updates the table layout and styling to make it aligned with the headers. 
Main things I did here are: 
- fix the column header width and the row cell width to be the same so they scale the same 
- account for the checkbox width
- update the truncated text to actually work. We had a bug where taliwind doesn't recognize partial classnames with dynamic variables in the className prop. You have to use a style prop. Read more [here](https://tailwindcss.com/docs/content-configuration#dynamic-class-names). 
- updated the width of the transformer button to fit in the column header with - this meant removing the "Select" frm the "Select Transformer" button text and just truncated it to "Transformer"
I kept the cells left aligned but we can easily center them if we'd like
Demo …

NEOS-1638: fixes table styling

---

backend/internal/cmds/mgmt/serve/connect/cmd.go
internal/ee/license/cascade.go
internal/ee/license/cloud.go
worker/internal/cmds/worker/serve/serve.go
worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go
worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity_test.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
worker/pkg/workflows/datasync/workflow/workflow.go
worker/pkg/workflows/datasync/workflow/workflow_integration_test.go

- Adds jobhooks activities for pre/post sync hooks to data sync workflow
- Updates worker to utilize generic EEInterface and wraps neosync cloud up into that for simplicity

NEOS-1643: Integrates JobHooks into Data Sync Workflow

---

backend/internal/connect/interceptors/auth_logging/interceptor_test.go
backend/internal/connect/interceptors/bookend/interceptor_test.go
backend/internal/connect/interceptors/logger/interceptor_test.go
backend/internal/connect/interceptors/logger/logger-ctx_test.go
backend/internal/neosyncdb/integration_test.go
backend/pkg/dbconnect-config/mysql_test.go
backend/pkg/dbconnect-config/postgres_test.go
backend/pkg/integration-test/integration-test.go
backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
go.mod
go.sum
internal/benthos/benthos-builder/builders/sql-util_test.go
internal/testutil/utils.go
worker/internal/temporal-logger/logger.go
worker/internal/temporal-logger/logger_test.go
worker/pkg/benthos/sql/output_sql_insert_test.go
worker/pkg/workflows/datasync/activities/account-status/activity_test.go
worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go
worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity_test.go
worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
worker/pkg/workflows/datasync/activities/post-table-sync/activity_test.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
worker/pkg/workflows/datasync/activities/sync-activity-opts/activity_test.go
worker/pkg/workflows/datasync/activities/sync-redis-clean-up/activity.go
worker/pkg/workflows/datasync/activities/sync/activity.go
worker/pkg/workflows/datasync/activities/sync/activity_test.go
worker/pkg/workflows/datasync/workflow/workflow_integration_test.go

Also updates a bunch of spots to use the testutil.GetLogger for tests

Wraps temporal logger in slog.Logger for better system plugin

---

backend/services/mgmt/v1alpha1/job-service/runs.go

This fixes a backend bug that was causing the sql query button to not render in the Runs page.

NEOS-1662: update GetJobRunEvents to properly parse metadata

---

frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx

The value we were using for the transformer column was too stable. it only took into account the case value, not the underlying config.
We make sure all transformer updates result in a fresh object, so returning the stable object reference is sufficient to trigger re-renders whenever the transformer itself is updated.
Due to this, the filterFn for the transformer needed to be updated to properly handle searches to retain the original functionality brought on by the old valueFn.
Demo: https://www.loom.com/share/6c7e422028cc40d699a6d58744976c00

NEOS-1663: Fixes transformer configs not updating in job mapping table

---

frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
frontend/apps/web/components/jobs/subsets/EditItem.tsx
frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx

This feature updates the subset page in the new job form and in the job edit form to:
1. Nests the sql editor into a dialog making it easier for customers to understand that you have to click on `Apply` and then the `Save` button instead of just clicking on Apply.
2. Fixes alignment issues in the subset table that were caused by long table names. We set the column width and the truncate text to the same width which keeps the table nicely aligned. 
Demo
https://www.loom.com/share/5831605332984d2d8968ce238e084a35

NEOS-1668. NEOS-1670: Align subset table

---

frontend/apps/web/components/jobs/subsets/EditItem.tsx
frontend/apps/web/components/jobs/subsets/ValidateQueryBadge.tsx
frontend/apps/web/components/jobs/subsets/subset-table/column.tsx

- sets column width on subset filter column so it doesnt throw off root column
- moves cancel and apply buttons to below editor

NEOS-1678: minor subset page styling updates

---

backend/pkg/sqlmanager/mysql/mysql-manager.go
backend/pkg/sqlmanager/postgres/postgres-manager.go
backend/services/mgmt/v1alpha1/job-service/runs.go
docs/docs/connections/postgres.md
docs/docs/guides/incremental-additions.md
frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
internal/ee/mssql-manager/ee-mssql-manager.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go

can't believe we didn't do this sooner.
fast follow is updating manager tests to further test this alongwith restructuring them to be faster

NEOS-1695: support creating schemas if they dont exist not just table

---

backend/internal/cmds/mgmt/serve/connect/cmd.go

This is preventing OSS helm charts from upgrading to v0.5 since it throws a license invalid error.

NEOS-1713: fixes run logs automatically turning on in k8s

---

frontend/apps/web/app/api/accounts/[accountId]/runs/[id]/logs/route.ts
frontend/apps/web/libs/hooks/useGetJobRunLogs.ts

The job run logs were totally broken, this was a regression from the migration to connection v2
Properly constructs the log query now too, which was a regression from moving to tanstack query. Now properly able to filter by log level.
This also fixes the logs not loading on initial page load because the loglevel default is 0, which marked it always as not ready.

NEOS-1605: Fixes job run logs not loading, fixes inability to specify log level

---

backend/services/mgmt/v1alpha1/job-service/runs.go
internal/javascript/vm/vm_test.go

this way users can come back to a job and always see the logs, at least longer than the current day.

NEOS-1724: updates runs logs query to use close time if workflow has ended

---

worker/pkg/benthos/transformer_executor/executor_test.go

fixes flaky generator test that would fail when we would generate a 3 word name.

NEOS-1726: updates test regex to be more permissive

---

python/src/neosync/__init__.py
python/src/neosync/__init__.pyi

I debugged this by installing neosync from pypi and noticing that the type hints werent really working.
I edited the module locally until vscode was able to properly find the type hints.
For whatever stupid reason both of these work, but only this diff fixes the type hints.
Tested with this script:
```
from neosync import Neosync, GetJobsRequest
client = Neosync(
api_url="localhost:8080",
insecure=True,
)
print(client)
jobs = client.jobs.GetJobs(
GetJobsRequest(account_id="c79eca6c-a9f8-40f4-9ca8-b0b8eb0d1a21")
)
print(jobs)
```

NEOS-1731: Fixes init types to properly handle python type hints

---

backend/gen/go/db/dbschemas/mysql/system.sql.go
backend/pkg/dbschemas/sql/mysql/queries/system.sql
backend/pkg/dbschemas/sql/mysql/schema/system.sql
backend/pkg/sqlmanager/mysql/mysql-manager.go
backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
backend/pkg/sqlmanager/mysql/testdata/setup.sql

Buried in the statistics table docs under the `Expression` column is the note that the `column name` is nullable.
> EXPRESSION
> 
> MySQL supports functional key parts (see [Functional Key Parts](https://dev.mysql.com/doc/refman/8.4/en/create-> index.html#create-index-functional-key-parts)), which affects both the COLUMN_NAME and EXPRESSION columns:
> 
> For a nonfunctional key part, COLUMN_NAME indicates the column indexed by the key part and EXPRESSION is NULL.
> 
> For a functional key part, COLUMN_NAME column is NULL and EXPRESSION indicates the expression for the key part.
This has now been fixed, with the mysql tests now properly handling a table index creation that is composite mixed with columns _and_ expressions.

NEOS-1730: mysql index statements broken when using non column

---

worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go

This causes the activity to stop too quickly instead of giving the worker time to gracefully shut down by letting the activities complete.

removes forceful stop channel in temporal activity

---

worker/pkg/workflows/datasync/activities/sync/activity.go
worker/pkg/workflows/datasync/activities/sync/activity_test.go

I missed this in the last PR
This allows the activity to gracefully finish when the worker has been signaled to shutdown instead of stopping immediately.
When it's actually time for a shutdown, the context will be canceled, which we are also handling.

Removes worker stop channel for sync activity

---

backend/pkg/dbconnect-config/mysql.go
backend/pkg/dbconnect-config/mysql_test.go

I've added a test to prove the issue, and fixed it.
Fixes #3220

Fix assignment to entry in nil map when providing attributes in mysql connection string

---

.gitignore
backend/internal/cmds/mgmt/serve/connect/cmd.go
backend/internal/connectiondata/connectiondata.go
backend/internal/connectiondata/gcp.go
backend/internal/gcp/client.go
backend/pkg/integration-test/mux.go
backend/services/mgmt/v1alpha1/job-service/service.go
internal/benthos/benthos-builder/builders/gcp-cloud-storage.go

this is tech debt that removes jobservice as dependency to connection data builder which I need to use in the job service

Update the Datastream endpoint GCS connection to retrieve the most recent run ID from storage instead of Temporal.

---

backend/gen/go/db/dbschemas/postgresql/system.sql.go
backend/pkg/dbschemas/sql/postgresql/queries/system.sql

this was causing a composite index to be returned as a duplicate value in the `linked_to_serial` query which was causing the `id` column to appear multiple times.

adds fix that filters out duplicate serials

---

backend/gen/go/db/dbschemas/postgresql/system.sql.go
backend/pkg/dbschemas/sql/postgresql/queries/system.sql
backend/pkg/sqlmanager/mysql/mysql-manager.go
backend/pkg/sqlmanager/postgres/postgres-manager.go
internal/ee/mssql-manager/ee-mssql-manager.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go

Swaps indexes to run before foreign keys due to unique indexes.
Tweaks the postgres query to remove extra indices being filtered. They are idempotent anyways.

tweaks pg index query, changes schema init ordering

---

backend/pkg/sqlmanager/postgres/postgres-manager.go
backend/services/mgmt/v1alpha1/job-service/jobs.go
worker/pkg/benthos/sql/input_sql_raw.go

Updates logic to use cursors instead of bringing all records into memory for more efficient memory handling and querying.

Use Postgres Cursors in selects for better memory management

---

backend/services/mgmt/v1alpha1/job-service/runs.go

With the update to use child workflows, the loki log query needs to use the JobRunId instead of WorkflowId to get all of the children.

fixes loki query to include child workflows

---

internal/javascript/functions/benthos/functions.go
internal/javascript/functions/functions.go
internal/javascript/functions/functions_test.go
internal/javascript/functions/neosync/functions.go
worker/pkg/benthos/javascript/benthos_value_api.go
worker/pkg/benthos/javascript/benthos_value_api_test.go
worker/pkg/benthos/javascript/processor.go
worker/pkg/benthos/javascript/processor_test.go

Updates JS function arg processing logic to be more defensive about types.
Adds many more tests to ensure these cases are handled.
Adds more panic recover handlers to trap unintended errors and to properly surface them to the user instead of crashing the process.

Makes JS VM Logic more defensive against panics

---

backend/internal/dtomaps/job-runs.go

fixes job run events message on frontend not surfacing enough details

---

frontend/apps/web/app/(mgmt)/[account]/settings/members/components/MemberTable.tsx
frontend/apps/web/app/invite/page.tsx
frontend/apps/web/components/providers/account-provider.tsx
frontend/apps/web/components/site-header/AccountStatusHandler.tsx
frontend/apps/web/components/site-header/Upgrade.tsx

- fixes upgrade button to not show for EE licensed installations
- adds local/session storage for account provider to handle tabs better
- slack and invite page no longer redirect away because there is no account in the url
- added more conditionals useAccount so that it ensures the user exists prior to retrieving the accounts.
- fixes bug on members page to conditionally show the update role only if rbac is enabled.

NEOS-1762: reworks account provider to handle selected account more effectively

---

worker/pkg/workflows/ee/account_hooks/workflow/workflow.go
worker/pkg/workflows/ee/account_hooks/workflow/workflow_test.go

for multiple account hooks this would be bad if one of them is not working correctly.
This way each one gets to run to its fullest and we return all of the hook failures as a single joined error message.

changes account hooks to not halt on first failure

---

backend/pkg/sqlmanager/postgres/postgres-manager.go
worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go

Since we create sequences first then tables in init schema the sequence names don't match the source db. Update postgres sequence reset to query destination instead of source for sequences to reset

Fixes postgres sequence reset

---

backend/internal/dtomaps/job-runs.go
backend/services/mgmt/v1alpha1/job-service/runs.go
frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable.tsx
frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
frontend/apps/web/components/RunTImeline/RunTimeline.tsx

For abandoned child workflows, this now handles retrieving the workflow history for that child to patch in synthetic event history for the main workflow.
This is only really useful right now for account hooks. But we could use it in the future to fully hydrate the child event history to surface all of it in the workflow.
Failed workflow now properly renders, even though it's a bit wonky:

adds in logic to handle abandoned child workflows in job run event history

---

frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx

Conditionally surfaces a button that pops all job mappings that are missing from the source form the table.
Currently only works for sync jobs on the edit page.

NEOS-1583: Adds ability to remove missing source columns from the mappings table

---

internal/integration-tests/worker/workflow/workflow-integration_test.go
internal/testutil/testdata/postgres/schema-init/alter-job-mappings.go
worker/pkg/query-builder/insert-query-builder.go

Not setting `OVERRIDING SYSTEM VALUE` when building postgres insert SQL with on conflict update set on a table with identity column was causing insert error

Fixes Postgres insert identity with OnConflict bug + fixes flaky postgres integration test

---

frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx

- Fixes transformer sorting
- Fixes transformer not being resettable back to unsorted state
- Adds multi sort (this is mostly relevant for sorting by table or schema, then by column.) not much will really happen the further right you go down the table due to not having any duplicates the lower you go.
Closes #3423

NEOS-1800: fixes transformer sorts, adds tooltip for multi sorting

---

worker/pkg/benthos/transformers/transform_full_name.go
worker/pkg/benthos/transformers/transform_full_name_test.go

fixes logic in fullname transformer with tests
