nucleuscloud/neosync

- frontend/app/jobs/[id]/components/PauseSwitch.tsx
- frontend/app/jobs/[id]/components/ScheduleCard.tsx
- frontend/app/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
- frontend/app/jobs/[id]/source/components/SourceConnectionCard.tsx
- frontend/app/runs/components/JobRunsTable/data-table-toolbar.tsx
- worker/internal/dbschemas/postgres/postgres.go
- fixed frontend form reset bugs
- fixed bug in worker where it couldn't generate create table statements for tables in the public schema
- fixed job runs table filter to be able to filter by job id
> fix small bugs

- frontend/app/connections/[id]/components/AwsS3Form.tsx
- frontend/app/connections/[id]/components/PostgresForm.tsx
- frontend/app/jobs/[id]/components/ScheduleCard.tsx
- frontend/app/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
- frontend/app/jobs/[id]/source/components/SourceConnectionCard.tsx
- frontend/app/jobs/[id]/util.ts
- frontend/app/new/job/schema.ts
- frontend/libs/hooks/useGetConnectionSchema.ts
- frontend/yup-validations/jobs.ts
fixed forms to use defaultValues and values field. this fixes the form data not being updated after submit
> Add source / destination unique validation in new job workflow

- frontend/app/new/job/schema/page.tsx
> fix job initiate on job creation

- frontend/components/jobs/SchemaTable/data-table.tsx
- frontend/components/ui/checkbox.tsx
- frontend/components/ui/tree.tsx
fixed checkbox indeterminate error
> Fix schema tree bugs

- backend/internal/utils/connections/mysql.go
- backend/services/mgmt/v1alpha1/connection-service/connection.go
- backend/services/mgmt/v1alpha1/connection-service/schema.go
- frontend/components/jobs/SchemaTable/data-table.tsx
- frontend/components/ui/tree.tsx
also made schema tree performance slightly better
> get mysql schema

- frontend/app/connections/page.tsx
- frontend/app/jobs/[id]/destinations/page.tsx
- frontend/app/jobs/[id]/source/components/SourceConnectionCard.tsx
- frontend/app/jobs/page.tsx
- frontend/app/new/connection/aws-s3/AwsS3Form.tsx
- frontend/app/new/connection/mysql/MysqlForm.tsx
- frontend/app/new/connection/postgres/PostgresForm.tsx
- frontend/app/new/job/[id]/destination/page.tsx
- frontend/app/new/job/flow/page.tsx
- frontend/app/new/job/schema/page.tsx
- frontend/app/new/job/subset/page.tsx
- frontend/app/new/transformer/page.tsx
- frontend/app/runs/components/RunsTable.tsx
- frontend/app/settings/temporal/components/TemporalConfigForm.tsx
- frontend/app/transformers/[id]/components/UpdateTransformerForm.tsx
- frontend/app/transformers/page.tsx
- frontend/components/AccountSwitcher.tsx
- frontend/components/SiteHeader.tsx
- frontend/components/jobs/SchemaTable/schema-table.tsx
- frontend/components/providers/account-provider.tsx
adds account switcher when auth is enabled
> add account switch

- .github/.devcontainer/devcontainer-lock.json
- .github/.devcontainer/devcontainer.json
- .github/workflows/artifact-release.yml
- .github/workflows/devcontainer-release.yml
* Adds zsh as default shell
* Updates devcontainer github action to use depot.dev for faster build times.
* Ran devcontainer update to grab latest feature dependencies
* Adds tiltfile extension to vscode settings
> Minor devcontainer updates

- frontend/app/new/account-api-key/NewApiKeyForm.tsx
- frontend/app/settings/account-api-keys/[id]/regenerate/page.tsx
> updates form description to show expiresAt expiration

- frontend/app/new/job/JobsProgressSteps.tsx
- frontend/components/progress-steps/Step.tsx
> make progress steps dark mode friendly

- frontend/app/jobs/[id]/components/JobPauseButton.tsx
- frontend/app/jobs/[id]/layout.tsx
* Fixes pause/resume button not properly re-rendering
* Updates to mutate correct API request to get latest status
* Adds spinner when trying
* Adds dedupe to prevent triggering request while one is currently trying
> fixes job pause button not re-rendering, adds spinner, dedupe

- backend/internal/auth/apikey/client.go
- backend/internal/auth/apikey/client_test.go
- cli/internal/auth/tokens.go
> Fix cli api key auth

- cli/internal/cmds/neosync/sync/sync.go
Only need to check for account id if using access token auth. If an api-key is provided no need to check because api-keys are scoped to a single account.
> Fix cli sync cmd api-key auth

- cli/internal/cmds/neosync/sync/sync.go
- cli/internal/output/output.go
add output flag to sync command options are plain, tty and auto
Fixes NEOS-486
> CLI - add sync output flag

- cli/internal/cmds/neosync/sync/sync.go
Fixes NEOS-486
https://github.com/charmbracelet/bubbletea/issues?page=3&q=is%3Aissue+is%3Aopen
> CLI - fix bubble tea plain mode

- frontend/apps/web/app/[account]/new/job/page.tsx
> Frontend - fix broken url

- frontend/apps/web/app/[account]/new/job/schema/page.tsx
- frontend/apps/web/yup-validations/jobs.ts
1. schema table not loading. missing account id in getSchema function
2. unable to save job where S3 is destination. missing s3 destination config
> Frontend - fix new job flow bugs

- frontend/apps/web/app/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
- frontend/apps/web/app/[account]/new/job/generate/single/schema/page.tsx
Fixes
- new generation job schema table not loading data because of missing account id
- generation job overview schema table not filtering by selected table
> Frontend - fix data generation schema table

- frontend/apps/web/app/[account]/connections/[id]/components/AwsS3Form.tsx
- frontend/apps/web/app/[account]/connections/[id]/components/connection-component.tsx
- frontend/apps/web/app/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
- frontend/apps/web/app/[account]/new/job/generate/single/schema/page.tsx
- frontend/apps/web/components/jobs/SchemaTable/VirtualizedSchemaTable.tsx
Fixes NEOS-493, NEOS-494
- S3 connection update not saving name or roleArn
- Adds error warning to data generation schema table
> Frontend - S3 connection form bug + Data gen schema table error alerts

- frontend/apps/web/app/[account]/settings/layout.tsx
- frontend/apps/web/app/[account]/settings/members/page.tsx
- frontend/apps/web/app/[account]/settings/page.tsx
- frontend/apps/web/libs/hooks/useGetSystemAppConfig.ts
api/config wasn't properly rendering this was causing issues when on teams accounts and for auth being enabled.
> Fixes Members Page Routing bug

- docs/docs/deploy/environment-variables.mdx
- docs/docs/transformers/system.mdx
> Fix Typos in Website

- worker/pkg/workflows/datasync/activities/benthos-builder.go
> generate job allow circular dependencies

- Tiltfile
- backend/charts/api/templates/deployment.yaml
- backend/charts/api/templates/hpa.yaml
- backend/charts/api/values.yaml
- tilt/metrics-server/Tiltfile
- worker/charts/worker/templates/deployment.yaml
- worker/charts/worker/templates/hpa.yaml
- worker/charts/worker/values.yaml
NEOS-580
Closes https://github.com/nucleuscloud/neosync/issues/1002
**TODO:**
> HPA templates to api and worker charts

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/NextRuns.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ScheduleCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/schema.ts
- frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformJavascriptForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/data-table-row-actions.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/systemTransformers/[name]/page.tsx
- frontend/apps/web/app/api/config/config.ts
- frontend/apps/web/components/VirtualizedTree.tsx
- frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
- frontend/apps/web/components/jobs/SchemaTable/VirtualizedSchemaTable.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx
- frontend/apps/web/components/site-header/AccountSwitcher.tsx
- frontend/apps/web/yup-validations/connections.ts
- frontend/apps/web/yup-validations/jobs.ts
> frontend - use js strict equality operator

- backend/charts/api/templates/api-env-vars.yaml
- backend/charts/api/values.yaml
- backend/internal/apikey/apikey.go
- backend/internal/apikey/apikey_test.go
- backend/internal/auth/apikey/client.go
- backend/internal/auth/apikey/client_test.go
- backend/internal/auth/authmw/auth.go
- backend/internal/auth/authmw/auth_test.go
- backend/internal/auth/authmw/mock_AuthClient.go
- backend/internal/auth/jwt/client.go
- backend/internal/auth/jwt/client_test.go
- backend/internal/cmds/mgmt/serve/connect/cmd.go
- backend/internal/connect/interceptors/auth/interceptor.go
- backend/internal/connect/interceptors/auth/interceptor_test.go
- backend/services/mgmt/v1alpha1/connection-service/connection_test.go
- backend/services/mgmt/v1alpha1/connection-service/user-account.go
- backend/services/mgmt/v1alpha1/job-service/jobs_test.go
- backend/services/mgmt/v1alpha1/job-service/user-account.go
- backend/services/mgmt/v1alpha1/transformers-service/transformers_test.go
- backend/services/mgmt/v1alpha1/transformers-service/user-account.go
* Adds new worker api key token type
* Updates api key middleware to support worker api keys
* api key mw supports a whitelist of api keys and procedures
* Updated relevant services to support worker api keys for the verify in account check
> Adds worker api key type

- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
> fix run activity table not expanding-

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
- frontend/apps/web/components/jobs/SchemaTable/VirtualizedSchemaTable.tsx
- frontend/apps/web/components/jobs/SchemaTable/schema-table.tsx
- frontend/apps/web/yup-validations/connections.ts
- frontend/apps/web/yup-validations/jobs.ts
fixes table not initially loading and table not updating when source is updated
> fix job mapping table

- worker/go.mod
not sure how github didnt catch this
> go work syncd go modules

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ActivitySyncOptionsCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/RecentRuns.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ScheduleCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/WorkflowSettingsCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/page.tsx
- frontend/apps/web/app/api/accounts/[accountId]/jobs/[id]/syncoptions/route.ts
- frontend/apps/web/app/api/accounts/[accountId]/jobs/[id]/workflowoptions/route.ts
- frontend/apps/web/components/ui/accordion.tsx
TODO: add this to the new job flow.
> Nick/neos 712 Adds advanced job run settings to job details page

- frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/components/ApiKeysTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/members/components/MemberTable.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateUserDefinedTransformerForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/SystemTransformersTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/SystemTransformersTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/SystemTransformersTable/data-table.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/data-table-pagination.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/data-table.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/systemTransformers/[name]/page.tsx
- frontend/apps/web/app/api/transformers/system/[source]/route.ts
- frontend/apps/web/libs/hooks/useGetSystemTransformerBySource.ts
* Adds source to system table, form
* When directing user back to /transformers from a detail page, now sets the correct tab of where they left off
* Removes abilitty to select table rows that did not need it
> NEOS-747 expose transformer source field in UI

- backend/pkg/sqlconnect/pgpool.go
- backend/pkg/sqlconnect/sql-connector.go
- backend/pkg/sqlconnect/sql-connector_test.go
- backend/pkg/sqlconnect/sqldb.go
also refactors the sql connector a little bit
> Adds missing tunnel close if sql connect fails

- worker/internal/cmds/worker/serve/serve.go
- worker/internal/http/client/client.go
- worker/internal/http/client/client_test.go
- worker/pkg/workflows/datasync/activities/activities.go
- worker/pkg/workflows/datasync/activities/activities_test.go
- worker/pkg/workflows/datasync/activities/benthos-builder.go
- worker/pkg/workflows/datasync/activities/benthos-builder_test.go
- worker/pkg/workflows/datasync/activities/shared/doc.go
- worker/pkg/workflows/datasync/activities/shared/shared.go
- worker/pkg/workflows/datasync/activities/sync/activity.go
- worker/pkg/workflows/datasync/activities/sync/activity_test.go
- worker/pkg/workflows/datasync/workflow/workflow.go
- worker/pkg/workflows/datasync/workflow/workflow_test.go
Also starts a new shared module that will be a centralized place for shared utils across the datasync activities
> Refactoring datasync Sync activity into its own module

- backend/gen/go/db/dbschemas/postgresql/system.sql.go
- backend/pkg/dbschemas/sql/postgresql/queries/system.sql
- backend/pkg/table-dependency/table-dependency_test.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
- worker/pkg/workflows/datasync/workflow/workflow.go
information_schema.constraint_column_usage postgres table read permission is too strict
> fix postgres foreign key query to use authorized table

- Makefile
Resolves issue 1480 ->  https://github.com/nucleuscloud/neosync/issues/1480
> corrected spelling compsoe -> compose in Makefile

- backend/charts/api/templates/deployment.yaml
> fixes default helm image for api

- compose/compose-otel.yml
- hack/otel-collector-config.yaml
- hack/prometheus.yaml
mostly used for local debug testing of metrics
> updates otel composee to include prom and grafana examples

- worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
- worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
- worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
also fix redis processor being invoked for null transformers on primary keys
> Fix build init statements - filter out dependencies not in job mappings

- frontend/apps/web/app/(mgmt)/[account]/new/connection/aws-s3/AwsS3Form.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
- frontend/apps/web/components/onboarding-checklist/OnboardingChecklist.tsx
* Re-enables onboarding checklist
* Fixes issue with onboarding state locally to not have to complete twice
* Fixes styling opacity issues
* Adds percentage to button
* Updates showGuide logic to be calculated
> NEOS-916 NEOS-925 - Re-enables onboarding checklist

- worker/pkg/workflows/datasync/activities/sync/conn-tunnel.go
- worker/pkg/workflows/datasync/activities/sync/conn-tunnel_test.go
> Add hardstop option to connection tunnel manager close

- frontend/apps/web/components/ListBox/ListBox.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
> NEOS-956 adds ability to pop column that no longer exists

- backend/gen/go/db/dbschemas/postgresql/system.sql.go
- backend/pkg/dbschemas/sql/postgresql/queries/system.sql
table names included schema for any table not in the public schema
> Fix postgres constraint query

- frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/data-table-column-header.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx
* Updates subset table to use virtualizer for improved performance
* Squashes schema/table into a single column to be uniform like the other tables
* Makes table and where columns searchable for easy filtering
> NEOS-1040: make subset table searchable

- backend/pkg/table-dependency/table-dependency.go
- backend/pkg/table-dependency/table-dependency_test.go
> Remove constraint check from run configs

- frontend/apps/web/app/(mgmt)/FormPersist.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/AiDataGenConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
- frontend/apps/web/app/(mgmt)/useFormPersist.tsx
Improves performance on AI Gen schema page.
See this for more issues on why I had to fork the useFormPersist hook: https://github.com/tiaanduplessis/react-hook-form-persist/issues/33
> NEOS-1061 Improves render performance on AI Generate Forms

- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/permissions/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/data-table-row-actions.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
- frontend/apps/web/app/(mgmt)/[account]/new/connection/components/ConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
- frontend/apps/web/components/CloneConnectionButton.tsx
Based on context, will send user to the new/connections page and will only show the appropriate connections to avoid confusion as to what is a valid connection to create given the context.
> NEOS-1049 Adds Connection Filtering when selecting NEW CONNECTION button

- worker/internal/benthos/transformers/generate_email_test.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
> updates blobl test to include passing in email_type

- frontend/apps/web/components/DualListBox/ColumnHeader.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/data-table-column-header.tsx
Exposes discrete schema/table columns to be added if desired.
removes Hide from dropdown as you can do the same thing in the View tab
Reduces border weight of listbox search input
makes similar changes to the subset table as the jobmapping table.
> tweaks job mapping table sorting/filtering

- frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateEmailForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformEmailForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformerForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
- frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateEmailForm.tsx
Allows specifying the email type for generate email transformers for uuid or fullname
> NEOS-1063 expose email type in GenerateEmail transform form

- worker/internal/benthos/utils.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/query-builder.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/query-builder_test.go
this only an issue with postgres
> Fix subsetting table with json column

- compose.yml
- hack/wait-for-it.sh
fixes issue where migration script would run prior to the api being ready
> fixes db seed script wait

- backend/services/mgmt/v1alpha1/metrics-service/metrics.go
This reverts commit 0ddce8665ad927c947a2f2a95b1df5529693c329.
> Revert "changing metrics step (#2005)"

- Makefile
- README.md
- backend/Makefile
- cli/Makefile
- docs/docs/deploy/authentication.md
- docs/docs/deploy/docker-compose.md
- docs/docs/guides/neosync-local-dev.md
- frontend/apps/web/package.json
- frontend/package.json
- frontend/packages/sdk/.eslintrc.json
- frontend/packages/sdk/package.json
- frontend/turbo.json
- worker/Makefile
Overalls root, backend, cli, worker makefiles.
frontend doesn't have one as it uses npm.
Help actually works.
Tries to make more commands available at the root.
> Overhauls Makefiles

- frontend/apps/web/components/jobs/SchemaTable/FormErrorsCard.tsx
> fixes size of validation reload icon

- backend/pkg/table-dependency/table-dependency.go
- backend/pkg/table-dependency/table-dependency_test.go
- backend/pkg/utils/utils.go
adds validation check for duplicate run configs
> Dedupe columns when creating run configs

- worker/pkg/workflows/datasync/workflow/workflow.go
> chore: update spelling error of columns in workflow error

- backend/pkg/table-dependency/table-dependency.go
- backend/pkg/table-dependency/table-dependency_test.go
> Fixes building duplicate run configs

- .github/workflows/go.yml
> Add github action that fails if go mod tidy results in git changes #2223

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/AiDataGenConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
- worker/pkg/benthos/openai_generate/openai_generate.go
- worker/pkg/benthos/openai_generate/openai_generate_test.go
> NEOS-1220: updating openai_generate to use csv instead of json

- frontend/apps/web/app/api/webhooks/keycloak/slack/route.ts
- frontend/apps/web/package.json
- frontend/package-lock.json
Realized we were only using got in one place and that all of the other webhooks had moved on to using fetch.
> Removes got usage from frontend in favor of fetch

- backend/pkg/table-dependency/table-dependency.go
- frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/generate.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-mongo.go
This does not cover javascript, only standard benthos mutations.
Also fixes inability to add javascript gen/trans from nosql mutation form
> NEOS-1300: add support for dynamodb key deep link for mutations

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
- frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
- frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
- frontend/apps/web/yup-validations/jobs.ts
* Source Options was only submittable for Dynamodb due to strange validation issues
* Fixes a few other issues with the Transformer form updates
> fixes source options form not being submittable, among others

- backend/pkg/sqlmanager/mysql/mysql-manager.go
- backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
- backend/pkg/sqlmanager/mysql/testdata/setup.sql
> NEOS-1311: syntax error neosyncaddindexifnotexists

- worker/pkg/benthos/default_transform/processor_test.go
- worker/pkg/benthos/dynamodb/output_test.go
- worker/pkg/benthos/transformers/transform_int64.go
- worker/pkg/benthos/transformers/utils/integer_utils.go
- worker/pkg/workflows/datasync/workflow/testdata/types.go
- worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Fixes bug with int64 transformer not converting any to int64
> Add dynamo output tests + default transformer processor test

- .github/workflows/go.yml
- worker/pkg/query-builder2/querybuilder.go
- worker/pkg/query-builder2/subset.go
- worker/pkg/workflows/datasync/activities/sync/activity_test.go
Store qualified where clause to reduce calls to postgres sql parser. Decreases worker integration tests time with -race flag
> Querybuilder optimizations

- worker/pkg/query-builder2/query-builder_integration_test.go
- worker/pkg/query-builder2/querybuilder.go
- worker/pkg/query-builder2/testdata/setup.sql
Seems to fix the base case.
Need to talk more about whether or not to left join.
> NEOS-1375: optimize querybuilder selects to conditionally add joins

- backend/pkg/mssql-querier/system.sql.go
- backend/pkg/sqlconnect/sql-connector.go
- backend/pkg/sqlmanager/mssql/mssql-manager.go
- compose.dev.yml
also fixes docker compose watch
> NEOS-1380: fixes sql server role permissions performance

- frontend/apps/web/components/ConfirmationDialog.tsx
- frontend/apps/web/components/DeleteConfirmationDialog.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
- frontend/apps/web/components/ui/alert-dialog.tsx
- frontend/apps/web/package.json
- frontend/package-lock.json
Also switches the confirm dialog over to using an alert
> NEOS-1408: add option to apply defaults to job mapping table

- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogsTable/data-table.tsx
- frontend/apps/web/components/ListBox/ListBox.tsx
- frontend/apps/web/components/jobs/NosqlTable/TableMappings/TableMappingsTable.tsx
- frontend/apps/web/components/jobs/SchemaTable/AiSchemaPageTable.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
- frontend/apps/web/components/jobs/SchemaTable/VirtualFkPageTable.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx
- frontend/apps/web/components/permissions/PermissionsDataTable.tsx
- frontend/apps/web/components/permissions/PermissionsDialog.tsx
Fixes the table height issue where there is no table height and has a scrollbar. Standardizes the table wrapper with styling and classnames.
> NEOS-1394:update tables

- frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
> NEOS:1416: simplify isDuplicate mapping logic for NoSql db

- backend/services/mgmt/v1alpha1/user-account-service/users.go
- frontend/apps/web/components/site-header/AccountSwitcher.tsx
I accidentally disabled the wrong thing
> NEOS-1415: enables account switcher in neosynccloud, disables create team for cloud

- backend/services/mgmt/v1alpha1/job-service/runs.go
- compose.dev.yml
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
- frontend/apps/web/components/CopyButton.tsx
- frontend/apps/web/package.json
- frontend/package-lock.json
https://www.loom.com/share/43ef79052a3449ec829b51a18c419061
^ Demo
Fast Follows:
- Update Dialog to use Monaco editor
- When piping into Monaco, would be great if we could run the SQL through a formatter so that it looks nicer.
- Add loading state when clicking on View button
This is an 80/20 PR to unblock folks that want to access the select queries.
> NEOS-1441: adds dialog for showing SELECT from job run

- backend/pkg/sqlmanager/mssql/mssql-manager.go
- worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
- worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
> Fix SQL Server identity column count after insert

- frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
- frontend/apps/web/tailwind.config.ts
Updates the Apply Default Transformers button copy as well as adds a disabled state when no tables are selected.
> NEOS-1442:disables the Apply Default Transformers button until a table is selected

- frontend/apps/web/components/jobs/Form/DynamoDBSourceOptionsForm.tsx
- frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
- frontend/apps/web/util/util.ts
Also centralizes a bunch of the transformer logic until a single utils file
> NEOS-1451: custom transformers not showing up in bulk set

- frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
If you clicked one of these badges it would submit the form 🤦
> updates tooltipproviders in attributes column to not be submit buttons

- frontend/apps/web/components/DualListBox/ColumnHeader.tsx
- frontend/apps/web/components/jobs/NosqlTable/TableMappings/ColumnHeader.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
- frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
- frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
https://www.loom.com/share/3e2a121068ef4436bf23083d602d1747
- Adds discrete search and filter boxes instead of popup menu
- Improves table alignment by removing hard widths
- Fixes sort state by adding the missing third state to turn off sorting
> Adds search input to job mapping table, fixes sort states

- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCardNumber.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCategoricalForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCountryForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateEmailForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateFloat64Form.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateGenderForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInt64Form.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInternationalPhoneNumberForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateJavascriptForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStateForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringPhoneNumberForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateUuidForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformE164PhoneNumberForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformEmailForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFirstNameForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFloat64Form.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFullNameForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64Form.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64PhoneForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformJavascriptForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformLastNameForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformPhoneNumberForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformStringForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
Replaces the transformer sheet with a dialog window. Also some minor styling and layout updates for the transformer forms that I've been meaning to resolve. 
https://www.loom.com/share/799487de89d9410084bc1bc06020aba0?sid=0f002fb9-74b6-4181-8fb7-31bf2ac93aad
> NEOS-1456: replaces the transformer sheet with a dialog

- worker/pkg/query-builder/query-builder.go
- worker/pkg/query-builder/query-builder_test.go
Fast follow add generate job integration test
> Fix query builder index out of range error

- docs/docs/transformers/system.md
- worker/pkg/benthos/transformers/generate_bool.go
- worker/pkg/benthos/transformers/generate_card_number.go
- worker/pkg/benthos/transformers/generate_country.go
- worker/pkg/benthos/transformers/generate_first_name.go
- worker/pkg/benthos/transformers/generate_float.go
- worker/pkg/benthos/transformers/generate_full_address.go
- worker/pkg/benthos/transformers/generate_gender.go
- worker/pkg/benthos/transformers/generate_int64.go
- worker/pkg/benthos/transformers/generate_int64_phone_number.go
- worker/pkg/benthos/transformers/generate_international_phone_number.go
- worker/pkg/benthos/transformers/generate_random_string.go
- worker/pkg/benthos/transformers/generate_sha256hash.go
- worker/pkg/benthos/transformers/generate_ssn.go
- worker/pkg/benthos/transformers/generate_state.go
- worker/pkg/benthos/transformers/generate_string_phone_number.go
- worker/pkg/benthos/transformers/generate_unix_timestamp.go
- worker/pkg/benthos/transformers/generate_zipcode.go
- worker/pkg/benthos/transformers/transform_character_scramble.go
- worker/pkg/benthos/transformers/transform_email.go
- worker/pkg/benthos/transformers/transform_float.go
- worker/pkg/benthos/transformers/transform_int64.go
- worker/pkg/benthos/transformers/transform_int64_phone_number.go
- worker/pkg/benthos/transformers/transform_lastname.go
- worker/pkg/benthos/transformers/transform_string.go
- worker/pkg/benthos/transformers/transform_string_phone_number.go
Updates the description field in the batch spec for many of the transformers. Also, updates the description in the docs to match just in case.
> NEOS-1467: update benthos specs and docs to match

- frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/NextRuns.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/components/ApiKeysTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/columns.tsx
Adds optional chaining to toDate() method in order to avoid toDate() does not exist errors
> NEOS-1248:add optional chaining to toDate() func to avoid "toDate() is not a function" errors

- frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
- frontend/apps/web/components/connections/TestConnectionBadge.tsx
Adds in real time connection checking in the Generate job Connect page similar to the Sync job page. 
https://www.loom.com/share/e30eb0f57c53460f96732dc33bc5f495?sid=59d8ae18-09a9-46c6-811a-431839e0778e
> NEOS-1419: add real time connection validation for the Generate job

- worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Only reset identity columns on tables that are in the job mapping
> Fix SQL Server identity reset bug

- docs/docs/deploy/kubernetes.md
PR #837 moved the location of the `helmfile.yaml`. This PR adjusts sources to changes.
> Updates dev frontend app helmfile reference in docs

- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
- frontend/apps/web/package.json
- frontend/package-lock.json
Also adds in a query formatted to display nicely.
https://www.loom.com/share/4d23df2e2370491baa476ea3d039a656
> Updates View Select Query to use Monaco Editor

- frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
https://www.loom.com/share/d2ca650959654b34ab6cd5c87f843404
> NEOS-1490: updates logic to apply passthrough to identity columns

- frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteUserForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/members/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/temporal/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/settings/usage/page.tsx
- frontend/apps/web/components/headers/SubPageHeader.tsx
Also updates account settings pages to all use the page sub header component for consistency.
> NEOS-1496: move invite member button to heading

- .github/workflows/repostats.yml
Generates a stats repo every day for long term github stats
> adds action to generate repo stats

- worker/pkg/benthos/transformers/transform_email.go
- worker/pkg/benthos/transformers/transformer_initializer.go
fixes transformer initialization
> Fix transform email in anonymize endpoint

- backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
- cli/internal/cmds/neosync/sync/sync.go
also fixes mysql truncate cascade check
> Fix connection data stream AWS S3 get latest job run

- cli/internal/cmds/neosync/sync/sync.go
this is just a start. need to add more debug statements
> Add debug flag to cli sync

- docs/protos/go.md
- docs/protos/home.md
- docs/protos/typescript.md
- docs/src/css/overrides.css
Updated typescript API docs with a little bit of a restructure and a few more examples.
> NEOS-1545: Update TS API Docs

- cli/internal/cmds/neosync/sync/sync.go
- cli/internal/cmds/neosync/sync/ui.go
> Add benthos standard log with table and runtype keyvals to CLI sync

- backend/internal/neosyncdb/integration_test.go
- backend/pkg/integration-test/integration-test-util.go
- backend/pkg/sqlmanager/mssql/integration_test.go
- backend/pkg/sqlmanager/mssql_sql-manager_integration_test.go
- backend/pkg/sqlmanager/mysql/integration_test.go
- backend/pkg/sqlmanager/mysql_sql-manager_integration_test.go
- backend/pkg/sqlmanager/postgres/integration_test.go
- backend/pkg/sqlmanager/postgres_sql-manager_integration_test.go
- backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
- cli/internal/cmds/neosync/sync/sync_integration_test.go
- internal/sshtunnel/dialer_integration_test.go
- internal/testutil/testdata/mysql/humanresources/create-schema.sql
- internal/testutil/testdata/mysql/humanresources/create-tables.sql
- internal/testutil/testdata/mysql/humanresources/teardown.sql
- worker/pkg/query-builder2/integration_test.go
- worker/pkg/query-builder2/query-builder_integration_test.go
- worker/pkg/workflows/datasync/workflow/integration_test.go
also cleans up postgres and mysql test containers
> Add CLI sync mysql integration test

- backend/sql/postgresql/models/transformers.go
> Fixes malformed struct tag in TransformFullName DB Model

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
- frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
- frontend/apps/web/components/jobs/Form/NewColumnAdditionStrategyOptionsForm.tsx
- frontend/apps/web/components/jobs/Form/PostgresDBSourceOptionsForm.tsx
- frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
- frontend/apps/web/yup-validations/jobs.ts
TODO:
- Will be following up with a dedicated Docs page that details what each strategy does and what types are supported.
- Will update frontend to include a link to the strategy page
> NEOS-1598: Updates Postgres Source Options to include New Column Addition Strategy

- docs/docs/connections/sqlserver.md
- docs/docs/guides/troubleshooting.md
- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/PostgresForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
- frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
- frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
- frontend/apps/web/yup-validations/connections.ts
- frontend/apps/web/yup-validations/number.ts
> NEOS-1602: expose sql connection options in app

- frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
- frontend/apps/web/components/FormHeader.tsx
- frontend/apps/web/components/NumberedInput.tsx
- frontend/apps/web/components/jobs/Form/AwsS3DestinationOptionsForm.tsx
- frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
- frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
- frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
- frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
- frontend/apps/web/yup-validations/jobs.ts
> NEOS-1590: exposes batching config sql options in app

- worker/pkg/benthos/sql/json_processor.go
fixes basic postgres arrays. more complicated array types are still broken
> Fix S3 to Postgres arrays

- cli/internal/cmds/neosync/sync/sync.go
- internal/postgres/utils.go
- worker/pkg/benthos/sql/json_processor.go
Fixes
- CLI sync account id logger tag
- s3 to postgres json arrays
- allow pg nil arrays when using passthrough
> Fixes Postgres jsonb in CLI sync

- backend/internal/cmds/mgmt/serve/connect/cmd.go
- backend/internal/connect/interceptors/accountid/interceptor.go
- backend/internal/connect/interceptors/accountid/interceptor_test.go
- backend/pkg/logger/logger.go
- backend/services/mgmt/v1alpha1/job-service/jobs.go
- go.mod
- go.sum
Looks for `GetAccountId` on the request and adds it to the ctx logger.
Also adds in dedupe of attrs
> Adds accountid unary interceptor to backend

- internal/postgres/utils.go
- internal/postgres/utils_test.go
- worker/pkg/benthos/sql/json_processor.go
- worker/pkg/benthos/sql/output_sql_insert.go
cleans up conversion from pgx to go types
> Fixes Postgres money and xml arrays in sync

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnApplyDefaultClick.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnTransformerBulkUpdateClick.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
- frontend/apps/web/components/jobs/SchemaTable/ApplyDefaultTransformersButton.tsx
Was going to add a loading state but all of these operations were blocking the UI anyways.
Instead I just optimized the set functions to be fast.
> NEOS-1628: Optimizes Bulk Set and Apply Default

- frontend/apps/web/app/(mgmt)/[account]/connections/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/HooksCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/NewHookButton.tsx
- frontend/apps/web/app/(mgmt)/[account]/jobs/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/components/RunsTable.tsx
- frontend/apps/web/app/(mgmt)/[account]/transformers/page.tsx
- frontend/apps/web/components/EmptyState.tsx
> NEOS-1656: adds empty state for job hooks

- frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
- frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
- frontend/apps/web/app/api/config/config.ts
- frontend/apps/web/app/config/app-config.ts
Moves Mongo, Dynamo, and MSSQL to no longer be experimental
Removes FFlags that disable dynamo and mssql
> Removes Experimental Connection Flags and unused FE feature flags

- go.mod
- go.sum
- internal/connectrpc/interceptors/retry/interceptor.go
- internal/connectrpc/interceptors/retry/interceptor_test.go
- worker/internal/cmds/worker/serve/serve.go
We are seeing a bit of jitter due to infra auto scaling, which this should help smooth over.
> Adds backoff interceptor to worker neosync clients

- internal/benthos/benthos-builder/builders/generate-ai.go
- internal/benthos/benthos-builder/builders/generate.go
- worker/pkg/benthos/config.go
- worker/pkg/benthos/error/output_error.go
- worker/pkg/benthos/utils.go
fallback and retry in wrong order. If insert fails it should check for critical error if not critical error it should retry processors / insert
> Fix generate jobs critical error check

- backend/gen/go/db/dbschemas/postgresql/system.sql.go
- backend/pkg/dbschemas/sql/postgresql/queries/system.sql
was causing duplicate identity columns to show up
> Fixes postgres identity column query

- worker/pkg/benthos/utils.go
handles `relation "public.table" does not exist` errors
> Adds table does not exist to critical errors list

- backend/internal/cmds/mgmt/serve/connect/cmd.go
- go.mod
- go.sum
- internal/pyroscope/logger/logger.go
- internal/pyroscope/pyroscope.go
- worker/internal/cmds/worker/serve/serve.go
Gives us better insight into performance monitoring
> Adds grafana pyroscope to worker and backend

- frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
- frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SampleTable/SampleTable.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SampleTable/SampleTableColumns.tsx
- worker/pkg/benthos/openai_generate/openai_generate.go
The sample was breaking if the column type was json.
> Updates Genai Job table to handle non-string columns

- docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
- docs/openapi/mgmt/v1alpha1/api_key.openapi.yaml
- docs/openapi/mgmt/v1alpha1/auth.openapi.yaml
- docs/openapi/mgmt/v1alpha1/connection.openapi.yaml
- docs/openapi/mgmt/v1alpha1/connection_data.openapi.yaml
- docs/openapi/mgmt/v1alpha1/job.openapi.yaml
- docs/openapi/mgmt/v1alpha1/metrics.openapi.yaml
- docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
- docs/openapi/mgmt/v1alpha1/user_account.openapi.yaml
- docs/openapi/neosync.mgmt.v1alpha1.yaml
- docs/package-lock.json
- docs/package.json
- neosync.openapi.template.yaml
- scripts/backend-gen.sh
Improves the user exp
- Bumps redocly generator to latest version
- bumps openapi connect generator from v0.13 to v0.15.3
> Fills out more metadata in openapi specs

- .github/workflows/go.yml
- backend/gen/go/db/dbschemas/postgresql/system.sql.go
- backend/pkg/dbschemas/sql/postgresql/queries/system.sql
- backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
- backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
- backend/pkg/sqlmanager/postgres/testdata/setup.sql
- backend/pkg/sqlretry/dbtx_retry.go
- cli/internal/cmds/neosync/sync/config.go
- internal/connectrpc/interceptors/retry/interceptor.go
- internal/connectrpc/interceptors/retry/interceptor_test.go
- internal/sshtunnel/dialer_integration_test.go
- internal/testutil/testcontainers/sqlserver/sqlserver.go
- worker/pkg/integration-test/dynamodb_test.go
Also fixes integration tests not fully running in the new format (doh)
The int test fix has exposed critical race errors that were being uncaught due to integration tests not running properly
> Fixes PG Data Type Arrays on schema init, re-enables integration tests in CI

- frontend/apps/web/libs/hooks/useGetTransformersHandler.ts
This shouldnt be visible yet as it's only available in the api
> removes transform pii text from frontend

- internal/temporal/clientmanager/manager.go
- worker/pkg/workflows/datasync/workflow/workflow.go
fast follow: use environment variable for maxConcurrency
> Adds table sync max  concurrency limit

- frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
- frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
- internal/benthos/benthos-builder/builders/gcp-cloud-storage.go
- internal/benthos/benthos-builder/builders/sql-util.go
also consolidates logic for computing default destination parameters
> Lowers max in flight on new jobs

- backend/internal/connectiondata/connectiondata.go
- frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
also fixes job mapping validation error on first page load saying that connection id is missing
fast follow: connection data service api tests for mssql
> Fix  connection data service not supporting SQLServer

- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
- frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
- frontend/apps/web/components/RunTImeline/RunTimeline.tsx
- worker/pkg/benthos/sql/input_sql_raw.go
- worker/pkg/benthos/sql/output_sql_insert.go
- worker/pkg/query-builder2/querybuilder.go
- worker/pkg/workflows/datasync/workflow/workflow.go
- Fixes lexicographical ordering for composite keys
- More frontend fixes for activities and child workflows that do not complete successfully
- Replaces truncate on insert with on conflict do nothing
> Fixes Lexico Ordering with paged queries

- backend/pkg/mssql-querier/system.sql.go
- backend/pkg/sqlmanager/mssql/mssql-manager.go
- backend/pkg/sqlmanager/sql-manager.go
- docs/docs/schema-init/overview.md
- docs/sidebars.ts
- internal/ee/mssql-manager/ee-mssql-manager.go
- internal/ee/mssql-manager/generate-sql.go
- internal/integration-tests/sqlmanager/mssql/mssql-manager_integration_test.go
- internal/integration-tests/sqlmanager/mssql/testdata/source-setup/009.sql
- internal/integration-tests/sqlmanager/mssql/testdata/source-setup/010.sql
also fixes create schema bug and updates docs
> NEOS-1753: Fixes SQLServer schema initialization for encrypted triggers

- backend/pkg/sqlretry/dbtx_retry.go
- backend/pkg/sqlretry/dbtx_retry_test.go
- internal/backoffutil/backoff-util.go
- internal/integration-tests/sshtunnel/dialer_integration_test.go
- internal/sshtunnel/dialer.go
- adds more error handling for sql networking errors
- Updates SSH Dialer to use backoff library instead of home grown logic
> Adds more handling for SQL Networking Errs, Updates SSH Dialer Backoff Strategy

- internal/benthos/benthos-builder/builders/sql.go
- internal/integration-tests/worker/workflow/postgres_test.go
> Fix SQL update processor removing primary key from message

- backend/gen/go/db/dbschemas/mysql/mock_Querier.go
- backend/gen/go/db/dbschemas/mysql/querier.go
- backend/gen/go/db/dbschemas/mysql/system.sql.go
- backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
- backend/gen/go/db/dbschemas/postgresql/querier.go
- backend/gen/go/db/dbschemas/postgresql/system.sql.go
- backend/pkg/dbschemas/sql/mysql/queries/system.sql
- backend/pkg/dbschemas/sql/mysql/schema/system.sql
- backend/pkg/dbschemas/sql/postgresql/queries/system.sql
- backend/pkg/mssql-querier/mock_Querier.go
- backend/pkg/mssql-querier/querier.go
- backend/pkg/mssql-querier/system.sql.go
- backend/pkg/sqlmanager/mock_SqlDatabase.go
- backend/pkg/sqlmanager/mssql/mssql-manager.go
- backend/pkg/sqlmanager/mysql/mysql-manager.go
- backend/pkg/sqlmanager/postgres/postgres-manager.go
- backend/pkg/sqlmanager/shared/types.go
- backend/pkg/sqlmanager/sql-manager.go
- internal/connectiondata/sql.go
- internal/integration-tests/sqlmanager/mssql/mssql-manager_integration_test.go
- internal/integration-tests/sqlmanager/mysql/mysql-manager_integration_test.go
- internal/integration-tests/sqlmanager/postgres/postgres-manager_integration_test.go
GetAllSchemas is going to be used by the frontend to surface the schemas list box.
> NEOS-1767: optimize pii detection getalltables sql method

- frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ActivitySyncOptionsCard.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/define/components/WorkflowSettings.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
- frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
> NEOS-1777: refactor workflow option labels to make sense for pii

- frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
> NEOS-1778: updates pii detection images and icon

- frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
one of the times the react linter error was right.
> NEOS-1786: fixes memoization of constraints in job mapping schema table

- internal/job/jobmapping-validator.go
- internal/job/jobmapping-validator_test.go
- internal/runconfigs/runconfigs.go
- internal/runconfigs/runconfigs_test.go
- worker/pkg/workflows/datasync/workflow/workflow.go
- worker/pkg/workflows/datasync/workflow/workflow_test.go
updates run configs dependency check to use the same logic as worker
> Fix jobmapping virtual foreign key validator + run configs run order validator

- backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
- backend/pkg/mssql-querier/mock_Querier.go
- backend/pkg/mssql-querier/querier.go
- backend/pkg/mssql-querier/system.sql.go
- backend/pkg/sqlmanager/mssql/mssql-manager.go
- internal/ee/mssql-manager/ee-mssql-manager.go
- internal/ee/mssql-manager/generate-sql.go
- internal/integration-tests/worker/workflow/mssql_test.go
- internal/testutil/testdata/mssql/alltypes/create-tables.sql
- internal/testutil/testdata/mssql/alltypes/job-mappings.go
Consolidates logic for sqlserver get database schema
> Fixes SQLServer generated columns default transformer not appearing on frontend

- worker/pkg/benthos/utils.go
https://www.postgresql.org/docs/current/errcodes-appendix.html
> NEOS-1809: adds more critical errors for on conflict and check constraints

- worker/pkg/benthos/openai_generate/openai_generate.go
- worker/pkg/benthos/utils.go
> Updates critical errors list to handle Mysql and SqlServer not null violations
